# steps:
# # - group: ":lock_with_ink_pen: Security Audits"
# #   key: "audits"
# #   steps:
# #   - label: ":brakeman: Brakeman"
# #     command: "if [[ -n \"$$BUILDKITE_RETRY_COUNT\" && \"$$BUILDKITE_RETRY_COUNT\" -gt 0 ]]; then\n  echo \"Retry detected, passing the step.\"\n  exit 0\nelse\n  echo \".buildkite/steps/brakemans\" \n  sleep 300\nfi\n"
# #     agents:
# #       hello: "1.9.4"
# #     retry:
# #       automatic:
# #       - exit_status: -1
# #         limit: 1
# #       - exit_status: 1
# #         limit: 1
# #       - exit_status: 255
# #         limit: 1
# #   - label: ":date: Outdated Check"
# #     command: echo ".buildkite/steps/outdated" && sleep 180
# #     #continue_on_failure: true

# # - group: "Linting"
# #   key: "linters"
# #   steps:
# #   - label: ":lint-roller: Linting task"
# #     command: "echo .buildkite/steps/linter"
# #   - label: ":lint-roller: Linting code"
# #     command: "echo .buildkite/steps/code-linteeeer"


steps:
- label: ":pipeline: Check for changes in pipeline1.yml or pipeline2.yml"
  plugins:
  - monorepo-diff#v1.0.1:
      watch:
      - path: pipeline1.yml
        config:
          command: |
            buildkite-agent meta-data set "pipeline1_triggered" "true"
            buildkite-agent pipeline upload pipeline1.yml
      - path: pipeline2.yml
        config:
          command: |
            buildkite-agent meta-data set "pipeline2_triggered" "true"
            buildkite-agent pipeline upload pipeline2.yml

- wait

- label: "Check if pipeline1.yml or pipeline2.yml was triggered"
  command: |
    pipeline1_triggered=$(buildkite-agent meta-data get 'pipeline1_triggered' --default 'false')
    pipeline2_triggered=$(buildkite-agent meta-data get 'pipeline2_triggered' --default 'false')

    if [[ "$pipeline1_triggered" == "true" ]]; then
      echo "pipeline1.yml was triggered"
    else
      echo "pipeline1.yml was not triggered"
    fi

    if [[ "$pipeline2_triggered" == "true" ]]; then
      echo "pipeline2.yml was triggered"
    else
      echo "pipeline2.yml was not triggered"
    fi




