steps:
- label: ":rocket: Build"
  command: |
    echo "Building"
  key: 'one'

- label: ":rocket: Build"
  command: echo "$$BUILDKITE_ORGANIZATION_SLUG"
  key: 'oneomne'


- block: ":rocket: Are we ready?"
  if: build.env("BUILDKITE_ORGANIZATION_SLUG") == 'personal-use-4'



# notify:
# - if: build.env("$$BUILDKITE_COMMAND_EXIT_STATUS") != 0
#   slack:
#     channels:
#     - "Support_test_account#training-and-testing"
#     message: "this is notification due to message condition meet"




# notify:
# - if: build.branch == pipeline.default_branch || build.message =~ /deploy/
#   slack:
#     channels:
#     - "Support_test_account#training-and-testing"
#     message: "this is notification due to message condition meet"

# notify:::::::
# # Notifying to support_test_account workspace and channek training-and-testing in that workspace
# - slack: "Support_test_account#training-and-testing"

# - label: ":danger: Terminating agents after usee"""""
#   command: "./agentkil.sh"

# notify:

#   -slack: "#slack_notification_test"

# - slack:
#     channels:
#     - "Support_test_account#training-and-testing"
#     message: "Hello I'm a custom success message"
#   if: build.state == "passed"
# - slack:
#     channels:
#     - "Support_test_account#training-and-testing"
#     message: "Hello I'm a custom failed message"
#   if: build.state == "failed"
