steps:
- label: ":rocket: Build"
  command: "echo 'Building abc.sh'"
  key: 'one'

# - label: ":danger: Terminating agents after use"
#   command: "./agentkil.sh"

notify:
  slack: "#Support_test_account#training-and-testing"
  if: build.state == "passed"
