steps:
- label: "Run Tests"
  command: buildkite-agent pipeline upload .buildkite/pipeline1.yml

- label: "Run Tests again"
  command: buildkite-agent pipeline upload .buildkite/pipeline2.yml

- label: "Run Tests 3"
  command: echo $$VARIABLE1
