steps:
- label: ":rocket: Build"
  command: "echo 'Building abc.sh'"
  key: 'one'

# - label: ":danger: Terminating agents after use"
#   command: "./agentkil.sh"
notify:

- label: ":rocket: Notify build passed or failed"
  command: "./test123.sh | buildkite-agent pipeline upload"
