steps:
- label: "Fail first, pass on retry"
  command: |
    #!/bin/bash

    # Define a file to store the attempt count
    ATTEMPT_FILE="attempt_count.txt"

    # Initialize the attempt count if the file does not exist
    if [ ! -f "$ATTEMPT_FILE" ]; then
      echo 0 > "$ATTEMPT_FILE"
    fi

    # Read the current attempt count
    ATTEMPT_COUNT=$(cat "$ATTEMPT_FILE")

    # Increment the attempt count
    ATTEMPT_COUNT=$((ATTEMPT_COUNT + 1))
    echo $ATTEMPT_COUNT > "$ATTEMPT_FILE"

    # Fail on the first attempt, pass on the second
    if [ "$ATTEMPT_COUNT" -lt 2 ]; then
      echo "Failing attempt $ATTEMPT_COUNT"
      # Exit with a non-zero exit code that is not 1
      exit 2
    else
      echo "Passing attempt $ATTEMPT_COUNT"
      # Cleanup: remove the attempt count file
      rm "$ATTEMPT_FILE"
      exit 0
    fi

  retry:
    automatic: true
    limit: 1
