steps:
- label: ":rocket: Build"
  command: "echo 'job id is $BUILDKITE_JOB_ID  and build id is $BUILDKITE_BUILD_ID'"
  key: 'one'

- label: ":rocket: Build"
  command: "echo \"$$BUILDKITE_ORGANIZATION_SLUG\""
  key: 'two'


- label: "List all environment variables in the job"
  command: |
    echo "job id is $BUILDKITE_JOB_ID  and build id is $BUILDKITE_BUILD_ID" | tee builder.log |grep 'job'

  artifact_paths: "builder.log"


# - label: ":cow: Buildkite exit status check
#   command: |
#     if [ "$$BUILDKITE_COMMAND_EXIT_STATUS" != 0 ]; then
#       cat << 'YAML' | buildkite-agent pipeline upload
#       steps:
#         - block: ":rocket: Are we ready?"
#     YAML
#     fi





# notify:
# - if: build.env("$$BUILDKITE_COMMAND_EXIT_STATUS") != 0
#   slack:
#     channels:
#     - "Support_test_account#training-and-testing"
#     message: "this is notification due to message condition meet"




# notify:
# - if: build.branch == pipeline.default_branch || build.message =~ /deploy/
#   slack:
#     channels:
#     - "Support_test_account#training-and-testing"
#     message: "this is notification due to message condition meet"

# notify:::::::
# # Notifying to support_test_account workspace and channek training-and-testing in that workspace
# - slack: "Support_test_account#training-and-testing"

# - label: ":danger: Terminating agents after usee"""""
#   command: "./agentkil.sh"

# notify:

#   -slack: "#slack_notification_test"

# - slack:
#     channels:
#     - "Support_test_account#training-and-testing"
#     message: "Hello I'm a custom success message"
#   if: build.state == "passed"
# - slack:
#     channels:
#     - "Support_test_account#training-and-testing"
#     message: "Hello I'm a custom failed message"
#   if: build.state == "failed"
