steps:
- group: ":lock_with_ink_pen: Security Audits"
  key: "audits"
  steps:
  - label: ":brakeman: Brakeman"
    command: "echo .buildkite/steps/brakeman"
  - label: ":yarn: Yarn Audit"
    command: |
      if [ -f /tmp/yarn_audit_retry ]; then
        echo "Retry detected, passing the step."
        exit 0
      else
        echo ".buildkite/steps/yarn && exit 1"
        touch /tmp/yarn_audit_retry
        exit 1
      fi
    retry:
      automatic:
      - exit_status: 1
        limit: 1
  - label: ":date: Outdated Check"
    command: "echo .buildkite/steps/outdated"
    # continue_on_failure: true

- group: "Linting"
  key: "linters"
  steps:
  - label: ":lint-roller: Linting task"
    command: "echo .buildkite/steps/linter"
  - label: ":lint-roller: Linting code"
    command: "echo .buildkite/steps/code-linter"
