steps:
- label: ":rocket: Build"
  command: |
    echo "Building"
  key: 'one'

- label: ":rocket: Build"
  command: echo "Building"
  key: 'oneomne'

notify:
- slack: "buildkite#slack_notification_test"

# - label: ":danger: Terminating agents after use"
#   command: "./agentkil.sh"

notify:

  -slack: "buildkite#slack_notification_test"

# - slack:
#     channels:
#     - "Support_test_account#training-and-testing"
#     message: "Hello I'm a custom success message"
#   if: build.state == "passed"
# - slack:
#     channels:
#     - "Support_test_account#training-and-testing"
#     message: "Hello I'm a custom failed message"
#   if: build.state == "failed"
