steps:
- label: ":rocket: Build"
  command: |
    echo "Building"
  key: 'one'

- label: ":rocket: Build"
  command: echo "Building"
  key: 'oneomne'

notify:
# Notifying to support_test_account workspace and channek training-and-testing in that workspace
- slack: "Support_test_account#training-and-testing"

# - label: ":danger: Terminating agents after use"
#   command: "./agentkil.sh"

# notify:

#   -slack: "#slack_notification_test"

# - slack:
#     channels:
#     - "Support_test_account#training-and-testing"
#     message: "Hello I'm a custom success message"
#   if: build.state == "passed"
# - slack:
#     channels:
#     - "Support_test_account#training-and-testing"
#     message: "Hello I'm a custom failed message"
#   if: build.state == "failed"
