#!/bin/bash
set -ueo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

foo() {
  time="$($DIR/benchmark exit 1)"

  if [ $? -ne 0 ]; then
    exit 1
  fi
}

if ! foo; then
  echo "Foo"
fi
